# Generated by Django 4.0.4 on 2022-04-21 21:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(max_length=6, null=True)),
                ('admission_date', models.DateField(auto_now=True)),
                ('image', models.CharField(max_length=500)),
                ('year_group', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(13)])),
                ('sex', models.CharField(max_length=6, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ManyToManyField(related_name='students', to='parents.parent')),
            ],
        ),
    ]
