# Generated by Django 4.0.4 on 2022-04-16 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(max_length=6)),
                ('admission_date', models.DateField(auto_now=True)),
                ('image', models.CharField(max_length=500)),
                ('year_group', models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(13)])),
                ('sex', models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
