# Generated by Django 4.0.4 on 2022-04-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
