# Generated by Django 4.0.4 on 2022-04-21 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_group',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(13)]),
        ),
    ]
