# Generated by Django 4.0.4 on 2022-04-21 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admission_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_group',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
