# Generated by Django 4.0.4 on 2022-04-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_customuser_parent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='parent_name',
            new_name='parent_id',
        ),
    ]
