# Generated by Django 4.0.4 on 2022-04-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_rename_parent_name_customuser_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='parent_id',
        ),
    ]
