# Generated by Django 4.0.4 on 2022-04-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_remove_customuser_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='parent',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
