# Generated by Django 4.0.4 on 2022-04-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('teachers', '0001_initial'),
        ('jwt_auth', '0007_alter_customuser_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomUser', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomUser', to='parents.parent'),
        ),
    ]
