# Generated by Django 4.0.4 on 2022-04-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_sex'),
        ('jwt_auth', '0008_customuser_teacher_alter_customuser_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomUser', to='students.student'),
        ),
    ]
