# Generated by Django 4.0.4 on 2022-04-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0009_customuser_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isParent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
