# Generated by Django 4.0.4 on 2022-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=100)),
                ('students', models.ManyToManyField(related_name='parent', to='students.student')),
            ],
        ),
    ]
