# Generated by Django 4.0.4 on 2022-04-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='students',
        ),
    ]
