# Generated by Django 4.0.4 on 2022-04-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_parent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='user',
            new_name='User',
        ),
    ]
