# Generated by Django 4.0.4 on 2022-04-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='recipient_parent_id',
        ),
    ]
