# Generated by Django 4.0.4 on 2022-04-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_basket_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='student',
        ),
    ]
