# Generated by Django 4.0.4 on 2022-04-17 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_remove_basket_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(13)]),
        ),
    ]
