# Generated by Django 4.0.4 on 2022-04-17 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_basket_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
