# Generated by Django 4.0.4 on 2022-04-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_alter_basket_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
