# Generated by Django 4.0.4 on 2022-04-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_parent'),
        ('basket', '0007_basket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='student',
        ),
        migrations.AddField(
            model_name='basket',
            name='student',
            field=models.ManyToManyField(related_name='baskets', to='students.student'),
        ),
    ]
