# Generated by Django 4.0.4 on 2022-04-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_parent'),
        ('basket', '0008_remove_basket_student_basket_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='student',
            field=models.ManyToManyField(null=True, related_name='baskets', to='students.student'),
        ),
    ]
